### ISSUE TITLE
PyStyle

### ISSUE THREAD

**Issue by CSM-BlueRed** [matxd291/matxd-debouncer#1]
![image](https://user-images.githubusercontent.com/89811976/201542550-b48bfd88-2ca6-455b-8b68-bd978a67a577.png)
T'utilise PyStyle pour le System et Colorama pour le style ya rien qui va xd

**Comment by matxd291** [comment]
mdrr je sais mais je vais faire une update tkt je l'avais a l'arrache a l'époque et g juste reposter

**Comment by matxd291** [comment]
mais sinon je vais corriger mtn tkt
